import Head from "next/head";
import ThreeTierPricing from "../components/ThreeTierPricing";
import styles from "../styles/Home.module.css";
import { ChakraProvider } from "@chakra-ui/react";
import BasicStatistics from "../components/BasicStatistics";
import Carousel from "../components/Carousel";
import GridBlurredBackdrop from "../components/Testimonials";
import SplitWithImage from "../components/Features";
import LargeWithAppLinksAndSocial from "../components/footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Carousel />
        <SplitWithImage />
        <ThreeTierPricing />
        <BasicStatistics />
        <GridBlurredBackdrop />
        <LargeWithAppLinksAndSocial />
      </main>
    </div>
  );
}

Home.getLayout = function getLayout(page, auth, theme) {
  return <ChakraProvider theme={theme}>{page}</ChakraProvider>;
};
